# import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
import = [
  "~/.config/alacritty/themes/gruvbox_material_medium_dark.toml",
	"~/.config/alacritty/key_bindings.yml",
]

[env]
TERM = "xterm-256color"

# [colors.primary]
# background = "#2b303a"  # sth wrong with nord.yml

[window]
opacity = 0.9

[window.dimensions]
columns = 160
lines = 48

[window.padding]
x = 0
y = 0

[scrolling]
multiplier = 8


# [font]
# size = 7.5

[font.normal]
family = "JetBrainsMonoNLNerdFont"
style = "Medium"

[font.bold]
family = "JetBrainsMonoNLNerdFont" 
style = "Bold"

[font.italic]
family = "JetBrainsMonoNLNerdFont"
style = "MediumItalic"

[font.bold_italic]
family = "JetBrainsMonoNLNerdFont"
style = "BoldItalic"
